version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.1
  aws-s3: circleci/aws-s3@4.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Build application
          command: go build -o myapp
      - run:
          name: Check for vulnerabilities
          command: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...
      - persist_to_workspace:
          root: .
          paths: myapp
      - store_artifacts:
          path: myapp
      - aws-cli/install:
          version: latest
      - aws-s3/sync:
          from: myapp
          to: 's3://cci-buket'

workflows:
  build-test-and-deploy:
    jobs:
      - build

